package com.shang.order.record;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.pay_no
     *
     * @mbggenerated
     */
    private String payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.city_id
     *
     * @mbggenerated
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.receiver_mobile
     *
     * @mbggenerated
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.receiver_name
     *
     * @mbggenerated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.disp_time
     *
     * @mbggenerated
     */
    private String dispTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.notify_time
     *
     * @mbggenerated
     */
    private String notifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.disp_date
     *
     * @mbggenerated
     */
    private Date dispDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.disp_type
     *
     * @mbggenerated
     */
    private String dispType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.order_type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.product_count
     *
     * @mbggenerated
     */
    private Integer productCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.check_code
     *
     * @mbggenerated
     */
    private String checkCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.cancel_reason
     *
     * @mbggenerated
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.province_id
     *
     * @mbggenerated
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.county_name
     *
     * @mbggenerated
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.county_id
     *
     * @mbggenerated
     */
    private String countyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.town_name
     *
     * @mbggenerated
     */
    private String townName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.towin_id
     *
     * @mbggenerated
     */
    private String towinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.payer_mobile
     *
     * @mbggenerated
     */
    private String payerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.detail_count
     *
     * @mbggenerated
     */
    private Integer detailCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.store_id
     *
     * @mbggenerated
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.store_name
     *
     * @mbggenerated
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order.commented
     *
     * @mbggenerated
     */
    private String commented;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.id
     *
     * @return the value of t_orderform_order.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.id
     *
     * @param id the value for t_orderform_order.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.pay_no
     *
     * @return the value of t_orderform_order.pay_no
     *
     * @mbggenerated
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.pay_no
     *
     * @param payNo the value for t_orderform_order.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.order_status
     *
     * @return the value of t_orderform_order.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.order_status
     *
     * @param orderStatus the value for t_orderform_order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.city_id
     *
     * @return the value of t_orderform_order.city_id
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.city_id
     *
     * @param cityId the value for t_orderform_order.city_id
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.address
     *
     * @return the value of t_orderform_order.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.address
     *
     * @param address the value for t_orderform_order.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.receiver_mobile
     *
     * @return the value of t_orderform_order.receiver_mobile
     *
     * @mbggenerated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.receiver_mobile
     *
     * @param receiverMobile the value for t_orderform_order.receiver_mobile
     *
     * @mbggenerated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.receiver_name
     *
     * @return the value of t_orderform_order.receiver_name
     *
     * @mbggenerated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.receiver_name
     *
     * @param receiverName the value for t_orderform_order.receiver_name
     *
     * @mbggenerated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.disp_time
     *
     * @return the value of t_orderform_order.disp_time
     *
     * @mbggenerated
     */
    public String getDispTime() {
        return dispTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.disp_time
     *
     * @param dispTime the value for t_orderform_order.disp_time
     *
     * @mbggenerated
     */
    public void setDispTime(String dispTime) {
        this.dispTime = dispTime == null ? null : dispTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.notify_time
     *
     * @return the value of t_orderform_order.notify_time
     *
     * @mbggenerated
     */
    public String getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.notify_time
     *
     * @param notifyTime the value for t_orderform_order.notify_time
     *
     * @mbggenerated
     */
    public void setNotifyTime(String notifyTime) {
        this.notifyTime = notifyTime == null ? null : notifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.disp_date
     *
     * @return the value of t_orderform_order.disp_date
     *
     * @mbggenerated
     */
    public Date getDispDate() {
        return dispDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.disp_date
     *
     * @param dispDate the value for t_orderform_order.disp_date
     *
     * @mbggenerated
     */
    public void setDispDate(Date dispDate) {
        this.dispDate = dispDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.disp_type
     *
     * @return the value of t_orderform_order.disp_type
     *
     * @mbggenerated
     */
    public String getDispType() {
        return dispType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.disp_type
     *
     * @param dispType the value for t_orderform_order.disp_type
     *
     * @mbggenerated
     */
    public void setDispType(String dispType) {
        this.dispType = dispType == null ? null : dispType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.order_type
     *
     * @return the value of t_orderform_order.order_type
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.order_type
     *
     * @param orderType the value for t_orderform_order.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.product_count
     *
     * @return the value of t_orderform_order.product_count
     *
     * @mbggenerated
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.product_count
     *
     * @param productCount the value for t_orderform_order.product_count
     *
     * @mbggenerated
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.user_id
     *
     * @return the value of t_orderform_order.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.user_id
     *
     * @param userId the value for t_orderform_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.create_time
     *
     * @return the value of t_orderform_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.create_time
     *
     * @param createTime the value for t_orderform_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.update_time
     *
     * @return the value of t_orderform_order.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.update_time
     *
     * @param updateTime the value for t_orderform_order.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.remark
     *
     * @return the value of t_orderform_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.remark
     *
     * @param remark the value for t_orderform_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.check_code
     *
     * @return the value of t_orderform_order.check_code
     *
     * @mbggenerated
     */
    public String getCheckCode() {
        return checkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.check_code
     *
     * @param checkCode the value for t_orderform_order.check_code
     *
     * @mbggenerated
     */
    public void setCheckCode(String checkCode) {
        this.checkCode = checkCode == null ? null : checkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.cancel_reason
     *
     * @return the value of t_orderform_order.cancel_reason
     *
     * @mbggenerated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.cancel_reason
     *
     * @param cancelReason the value for t_orderform_order.cancel_reason
     *
     * @mbggenerated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.province_name
     *
     * @return the value of t_orderform_order.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.province_name
     *
     * @param provinceName the value for t_orderform_order.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.province_id
     *
     * @return the value of t_orderform_order.province_id
     *
     * @mbggenerated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.province_id
     *
     * @param provinceId the value for t_orderform_order.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.county_name
     *
     * @return the value of t_orderform_order.county_name
     *
     * @mbggenerated
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.county_name
     *
     * @param countyName the value for t_orderform_order.county_name
     *
     * @mbggenerated
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.county_id
     *
     * @return the value of t_orderform_order.county_id
     *
     * @mbggenerated
     */
    public String getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.county_id
     *
     * @param countyId the value for t_orderform_order.county_id
     *
     * @mbggenerated
     */
    public void setCountyId(String countyId) {
        this.countyId = countyId == null ? null : countyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.town_name
     *
     * @return the value of t_orderform_order.town_name
     *
     * @mbggenerated
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.town_name
     *
     * @param townName the value for t_orderform_order.town_name
     *
     * @mbggenerated
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.towin_id
     *
     * @return the value of t_orderform_order.towin_id
     *
     * @mbggenerated
     */
    public String getTowinId() {
        return towinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.towin_id
     *
     * @param towinId the value for t_orderform_order.towin_id
     *
     * @mbggenerated
     */
    public void setTowinId(String towinId) {
        this.towinId = towinId == null ? null : towinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.city_name
     *
     * @return the value of t_orderform_order.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.city_name
     *
     * @param cityName the value for t_orderform_order.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.payer_mobile
     *
     * @return the value of t_orderform_order.payer_mobile
     *
     * @mbggenerated
     */
    public String getPayerMobile() {
        return payerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.payer_mobile
     *
     * @param payerMobile the value for t_orderform_order.payer_mobile
     *
     * @mbggenerated
     */
    public void setPayerMobile(String payerMobile) {
        this.payerMobile = payerMobile == null ? null : payerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.detail_count
     *
     * @return the value of t_orderform_order.detail_count
     *
     * @mbggenerated
     */
    public Integer getDetailCount() {
        return detailCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.detail_count
     *
     * @param detailCount the value for t_orderform_order.detail_count
     *
     * @mbggenerated
     */
    public void setDetailCount(Integer detailCount) {
        this.detailCount = detailCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.store_id
     *
     * @return the value of t_orderform_order.store_id
     *
     * @mbggenerated
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.store_id
     *
     * @param storeId the value for t_orderform_order.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.store_name
     *
     * @return the value of t_orderform_order.store_name
     *
     * @mbggenerated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.store_name
     *
     * @param storeName the value for t_orderform_order.store_name
     *
     * @mbggenerated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order.commented
     *
     * @return the value of t_orderform_order.commented
     *
     * @mbggenerated
     */
    public String getCommented() {
        return commented;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order.commented
     *
     * @param commented the value for t_orderform_order.commented
     *
     * @mbggenerated
     */
    public void setCommented(String commented) {
        this.commented = commented == null ? null : commented.trim();
    }
}