package com.shang.order.record;

import java.math.BigDecimal;

public class OrderDtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.product_image
     *
     * @mbggenerated
     */
    private String productImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.product_content
     *
     * @mbggenerated
     */
    private String productContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.product_count
     *
     * @mbggenerated
     */
    private Integer productCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.product_price
     *
     * @mbggenerated
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.order_pay_no
     *
     * @mbggenerated
     */
    private String orderPayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.menu_id
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_order_detail.subtotal
     *
     * @mbggenerated
     */
    private BigDecimal subtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.id
     *
     * @return the value of t_orderform_order_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.id
     *
     * @param id the value for t_orderform_order_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.order_id
     *
     * @return the value of t_orderform_order_detail.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.order_id
     *
     * @param orderId the value for t_orderform_order_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.product_id
     *
     * @return the value of t_orderform_order_detail.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.product_id
     *
     * @param productId the value for t_orderform_order_detail.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.product_image
     *
     * @return the value of t_orderform_order_detail.product_image
     *
     * @mbggenerated
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.product_image
     *
     * @param productImage the value for t_orderform_order_detail.product_image
     *
     * @mbggenerated
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.product_name
     *
     * @return the value of t_orderform_order_detail.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.product_name
     *
     * @param productName the value for t_orderform_order_detail.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.product_content
     *
     * @return the value of t_orderform_order_detail.product_content
     *
     * @mbggenerated
     */
    public String getProductContent() {
        return productContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.product_content
     *
     * @param productContent the value for t_orderform_order_detail.product_content
     *
     * @mbggenerated
     */
    public void setProductContent(String productContent) {
        this.productContent = productContent == null ? null : productContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.product_count
     *
     * @return the value of t_orderform_order_detail.product_count
     *
     * @mbggenerated
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.product_count
     *
     * @param productCount the value for t_orderform_order_detail.product_count
     *
     * @mbggenerated
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.product_price
     *
     * @return the value of t_orderform_order_detail.product_price
     *
     * @mbggenerated
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.product_price
     *
     * @param productPrice the value for t_orderform_order_detail.product_price
     *
     * @mbggenerated
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.order_pay_no
     *
     * @return the value of t_orderform_order_detail.order_pay_no
     *
     * @mbggenerated
     */
    public String getOrderPayNo() {
        return orderPayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.order_pay_no
     *
     * @param orderPayNo the value for t_orderform_order_detail.order_pay_no
     *
     * @mbggenerated
     */
    public void setOrderPayNo(String orderPayNo) {
        this.orderPayNo = orderPayNo == null ? null : orderPayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.menu_id
     *
     * @return the value of t_orderform_order_detail.menu_id
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.menu_id
     *
     * @param menuId the value for t_orderform_order_detail.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_order_detail.subtotal
     *
     * @return the value of t_orderform_order_detail.subtotal
     *
     * @mbggenerated
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_order_detail.subtotal
     *
     * @param subtotal the value for t_orderform_order_detail.subtotal
     *
     * @mbggenerated
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
}