package com.shang.order.record;

import java.math.BigDecimal;
import java.util.Date;

public class PayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.order_type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.order_count
     *
     * @mbggenerated
     */
    private Integer orderCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.disp_type
     *
     * @mbggenerated
     */
    private String dispType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.pay_type
     *
     * @mbggenerated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.topay
     *
     * @mbggenerated
     */
    private BigDecimal topay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.disp_cost
     *
     * @mbggenerated
     */
    private BigDecimal dispCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.pay_amount
     *
     * @mbggenerated
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.agreement_id
     *
     * @mbggenerated
     */
    private Integer agreementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.weixin
     *
     * @mbggenerated
     */
    private BigDecimal weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.point_name
     *
     * @mbggenerated
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.point_value
     *
     * @mbggenerated
     */
    private BigDecimal pointValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.promotion_info
     *
     * @mbggenerated
     */
    private String promotionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.promotion_value
     *
     * @mbggenerated
     */
    private BigDecimal promotionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.code_name
     *
     * @mbggenerated
     */
    private String codeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.code_value
     *
     * @mbggenerated
     */
    private BigDecimal codeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.point_times
     *
     * @mbggenerated
     */
    private Integer pointTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.order_source
     *
     * @mbggenerated
     */
    private String orderSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderform_pay.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.id
     *
     * @return the value of t_orderform_pay.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.id
     *
     * @param id the value for t_orderform_pay.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.order_type
     *
     * @return the value of t_orderform_pay.order_type
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.order_type
     *
     * @param orderType the value for t_orderform_pay.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.order_count
     *
     * @return the value of t_orderform_pay.order_count
     *
     * @mbggenerated
     */
    public Integer getOrderCount() {
        return orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.order_count
     *
     * @param orderCount the value for t_orderform_pay.order_count
     *
     * @mbggenerated
     */
    public void setOrderCount(Integer orderCount) {
        this.orderCount = orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.disp_type
     *
     * @return the value of t_orderform_pay.disp_type
     *
     * @mbggenerated
     */
    public String getDispType() {
        return dispType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.disp_type
     *
     * @param dispType the value for t_orderform_pay.disp_type
     *
     * @mbggenerated
     */
    public void setDispType(String dispType) {
        this.dispType = dispType == null ? null : dispType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.pay_status
     *
     * @return the value of t_orderform_pay.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.pay_status
     *
     * @param payStatus the value for t_orderform_pay.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.pay_type
     *
     * @return the value of t_orderform_pay.pay_type
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.pay_type
     *
     * @param payType the value for t_orderform_pay.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.total_price
     *
     * @return the value of t_orderform_pay.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.total_price
     *
     * @param totalPrice the value for t_orderform_pay.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.discount
     *
     * @return the value of t_orderform_pay.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.discount
     *
     * @param discount the value for t_orderform_pay.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.topay
     *
     * @return the value of t_orderform_pay.topay
     *
     * @mbggenerated
     */
    public BigDecimal getTopay() {
        return topay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.topay
     *
     * @param topay the value for t_orderform_pay.topay
     *
     * @mbggenerated
     */
    public void setTopay(BigDecimal topay) {
        this.topay = topay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.disp_cost
     *
     * @return the value of t_orderform_pay.disp_cost
     *
     * @mbggenerated
     */
    public BigDecimal getDispCost() {
        return dispCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.disp_cost
     *
     * @param dispCost the value for t_orderform_pay.disp_cost
     *
     * @mbggenerated
     */
    public void setDispCost(BigDecimal dispCost) {
        this.dispCost = dispCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.pay_amount
     *
     * @return the value of t_orderform_pay.pay_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.pay_amount
     *
     * @param payAmount the value for t_orderform_pay.pay_amount
     *
     * @mbggenerated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.create_time
     *
     * @return the value of t_orderform_pay.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.create_time
     *
     * @param createTime the value for t_orderform_pay.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.pay_time
     *
     * @return the value of t_orderform_pay.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.pay_time
     *
     * @param payTime the value for t_orderform_pay.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.user_id
     *
     * @return the value of t_orderform_pay.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.user_id
     *
     * @param userId the value for t_orderform_pay.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.agreement_id
     *
     * @return the value of t_orderform_pay.agreement_id
     *
     * @mbggenerated
     */
    public Integer getAgreementId() {
        return agreementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.agreement_id
     *
     * @param agreementId the value for t_orderform_pay.agreement_id
     *
     * @mbggenerated
     */
    public void setAgreementId(Integer agreementId) {
        this.agreementId = agreementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.weixin
     *
     * @return the value of t_orderform_pay.weixin
     *
     * @mbggenerated
     */
    public BigDecimal getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.weixin
     *
     * @param weixin the value for t_orderform_pay.weixin
     *
     * @mbggenerated
     */
    public void setWeixin(BigDecimal weixin) {
        this.weixin = weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.balance
     *
     * @return the value of t_orderform_pay.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.balance
     *
     * @param balance the value for t_orderform_pay.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.point_name
     *
     * @return the value of t_orderform_pay.point_name
     *
     * @mbggenerated
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.point_name
     *
     * @param pointName the value for t_orderform_pay.point_name
     *
     * @mbggenerated
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.point_value
     *
     * @return the value of t_orderform_pay.point_value
     *
     * @mbggenerated
     */
    public BigDecimal getPointValue() {
        return pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.point_value
     *
     * @param pointValue the value for t_orderform_pay.point_value
     *
     * @mbggenerated
     */
    public void setPointValue(BigDecimal pointValue) {
        this.pointValue = pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.promotion_info
     *
     * @return the value of t_orderform_pay.promotion_info
     *
     * @mbggenerated
     */
    public String getPromotionInfo() {
        return promotionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.promotion_info
     *
     * @param promotionInfo the value for t_orderform_pay.promotion_info
     *
     * @mbggenerated
     */
    public void setPromotionInfo(String promotionInfo) {
        this.promotionInfo = promotionInfo == null ? null : promotionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.promotion_value
     *
     * @return the value of t_orderform_pay.promotion_value
     *
     * @mbggenerated
     */
    public BigDecimal getPromotionValue() {
        return promotionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.promotion_value
     *
     * @param promotionValue the value for t_orderform_pay.promotion_value
     *
     * @mbggenerated
     */
    public void setPromotionValue(BigDecimal promotionValue) {
        this.promotionValue = promotionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.code_name
     *
     * @return the value of t_orderform_pay.code_name
     *
     * @mbggenerated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.code_name
     *
     * @param codeName the value for t_orderform_pay.code_name
     *
     * @mbggenerated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.code_value
     *
     * @return the value of t_orderform_pay.code_value
     *
     * @mbggenerated
     */
    public BigDecimal getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.code_value
     *
     * @param codeValue the value for t_orderform_pay.code_value
     *
     * @mbggenerated
     */
    public void setCodeValue(BigDecimal codeValue) {
        this.codeValue = codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.point_times
     *
     * @return the value of t_orderform_pay.point_times
     *
     * @mbggenerated
     */
    public Integer getPointTimes() {
        return pointTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.point_times
     *
     * @param pointTimes the value for t_orderform_pay.point_times
     *
     * @mbggenerated
     */
    public void setPointTimes(Integer pointTimes) {
        this.pointTimes = pointTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.order_source
     *
     * @return the value of t_orderform_pay.order_source
     *
     * @mbggenerated
     */
    public String getOrderSource() {
        return orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.order_source
     *
     * @param orderSource the value for t_orderform_pay.order_source
     *
     * @mbggenerated
     */
    public void setOrderSource(String orderSource) {
        this.orderSource = orderSource == null ? null : orderSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderform_pay.group_id
     *
     * @return the value of t_orderform_pay.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderform_pay.group_id
     *
     * @param groupId the value for t_orderform_pay.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }
}