package com.shang.order.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.shang.order.record.PayInfo;
import com.shang.order.record.PayInfoExample;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int countByExample(PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int deleteByExample(PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    List<PayInfo> selectByExample(PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    PayInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PayInfo record, @Param("example") PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PayInfo record, @Param("example") PayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderform_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayInfo record);
}